### ISSUE TITLE
Serf crashes on (malformed?) message

### ISSUE THREAD

**Issue by jacksontj** [hashicorp/serf#339]
Over the last few weeks on the side I've been playing around with a gossip library for python. After I got one working I've started looking into making mine wire-compatible with memberlist-- which is actually coming along quite well. As part of that effort I've begun testing my code against serf (since its a nice standalone usage of memberlist). While testing the tcp state syncing, I found a reproducible case that causes the serf agent to crash. I'm not certain at this point if my message is malformed (doesn't seem to be, but I'm still looking into that). Regardless, being able to send some stuff over TCP and crashing serf seems like a problem-- so I figured I'd report the issue.

Python code to cause the crash:

```
import socket
import msgpack
import struct

if __name__ == '__main__':
    # Create a TCP/IP socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    # Connect the socket to the port where the server is listening
    server_address = ('localhost', 7946)
    sock.connect(server_address)

    packer = msgpack.Packer()
    ret = [struct.pack('!B', 6)]
    ret.append(packer.pack({
        'Nodes': 0,
        'UserStateLen': 0,
        'Join': False,
    }))


    sock.send(''.join(ret))
```

Example backtrace from serf:

```
Example output from serf
[jacksontj@Thomas-PC serf]$ ./serf agent
==> Starting Serf agent...
==> Starting Serf agent RPC...
==> Serf agent running!
         Node name: 'Thomas-PC.jacksontj.dyndns.org'
         Bind addr: '0.0.0.0:7946'
          RPC addr: '127.0.0.1:7373'
         Encrypted: false
          Snapshot: false
           Profile: lan

==> Log data will now stream in as it occurs:

    2015/11/09 08:41:52 [INFO] agent: Serf agent starting
    2015/11/09 08:41:52 [INFO] serf: EventMemberJoin: Thomas-PC.jacksontj.dyndns.org 10.0.1.113



    2015/11/09 08:41:53 [INFO] agent: Received event: member-join
    2015/11/09 08:41:54 [ERR] memberlist: Failed to receive remote state: EOF
    2015/11/09 08:42:12 [ERR] memberlist: Failed to receive remote state: EOF
panic: runtime error: index out of range

goroutine 29 [running]:
github.com/hashicorp/serf/serf.(*delegate).MergeRemoteState(0xc20804a110, 0x0, 0x0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/delegate.go:174 +0xa0c
github.com/hashicorp/memberlist.(*Memberlist).handleConn(0xc2080880e0, 0xc20804a0b8)
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/net.go:235 +0xb18
created by github.com/hashicorp/memberlist.(*Memberlist).tcpListen
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/net.go:182 +0x14c

goroutine 1 [select]:
github.com/hashicorp/serf/command/agent.(*Command).handleSignals(0xc20804c910, 0xc2080cc3c0, 0xc208010b60, 0xc208058a80, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/command/agent/command.go:565 +0x9d2
github.com/hashicorp/serf/command/agent.(*Command).Run(0xc20804c910, 0xc20800a010, 0x0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/command/agent/command.go:554 +0x95a
github.com/mitchellh/cli.(*CLI).Run(0xc20805d220, 0xc2080311b0, 0x0, 0x0)
	/Users/armon/projects/go/src/github.com/mitchellh/cli/cli.go:100 +0x3ce
main.realMain(0x40344a)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/main.go:37 +0x36c
main.main()
	/Users/armon/projects/go/src/github.com/hashicorp/serf/main.go:12 +0x1f

goroutine 5 [syscall]:
os/signal.loop()
	/Users/armon/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/Users/armon/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [select]:
github.com/armon/go-metrics.(*InmemSignal).run(0xc20803dc40)
	/Users/armon/projects/go/src/github.com/armon/go-metrics/inmem_signal.go:63 +0xf1
created by github.com/armon/go-metrics.NewInmemSignal
	/Users/armon/projects/go/src/github.com/armon/go-metrics/inmem_signal.go:37 +0x258

goroutine 8 [sleep]:
github.com/armon/go-metrics.(*Metrics).collectStats(0xc20804cb90)
	/Users/armon/projects/go/src/github.com/armon/go-metrics/metrics.go:67 +0x2c
created by github.com/armon/go-metrics.New
	/Users/armon/projects/go/src/github.com/armon/go-metrics/start.go:61 +0xe8

goroutine 9 [select]:
github.com/hashicorp/serf/serf.coalesceLoop(0xc208058480, 0xc208058300, 0xc208058420, 0xb2d05e00, 0x3b9aca00, 0x7fc39cbcda70, 0xc208031420)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/coalesce.go:44 +0x279
created by github.com/hashicorp/serf/serf.coalescedEventCh
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/coalesce.go:26 +0x8c

goroutine 10 [select]:
github.com/hashicorp/serf/serf.coalesceLoop(0xc2080584e0, 0xc208058480, 0xc208058420, 0xb2d05e00, 0x3b9aca00, 0x7fc39cbcdaa8, 0xc20804a0f8)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/coalesce.go:44 +0x279
created by github.com/hashicorp/serf/serf.coalescedEventCh
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/coalesce.go:26 +0x8c

goroutine 11 [select]:
github.com/hashicorp/serf/serf.(*serfQueries).stream(0xc208094750)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/internal_query.go:80 +0x288
created by github.com/hashicorp/serf/serf.newSerfQueries
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/internal_query.go:73 +0x137

goroutine 12 [IO wait]:
net.(*pollDesc).Wait(0xc208010d10, 0x72, 0x0, 0x0)
	/Users/armon/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010d10, 0x0, 0x0)
	/Users/armon/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010cb0, 0x0, 0x7fc39cbccd70, 0xc208031ab0)
	/Users/armon/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20804a118, 0xc20804a0b8, 0x0, 0x0)
	/Users/armon/go/src/net/tcpsock_posix.go:234 +0x4e
github.com/hashicorp/memberlist.(*Memberlist).tcpListen(0xc2080880e0)
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/net.go:174 +0x2f
created by github.com/hashicorp/memberlist.newMemberlist
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/memberlist.go:122 +0xe83

goroutine 13 [IO wait]:
net.(*pollDesc).Wait(0xc208010d80, 0x72, 0x0, 0x0)
	/Users/armon/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010d80, 0x0, 0x0)
	/Users/armon/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc208010d20, 0xc2080f0000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x7fc39cbccd70, 0xc208031790)
	/Users/armon/go/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc20804a120, 0xc2080f0000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x0)
	/Users/armon/go/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc20804a120, 0xc2080f0000, 0x10000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x0)
	/Users/armon/go/src/net/udpsock_posix.go:82 +0x12e
github.com/hashicorp/memberlist.(*Memberlist).udpListen(0xc2080880e0)
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/net.go:259 +0x2f2
created by github.com/hashicorp/memberlist.newMemberlist
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/memberlist.go:123 +0xea3

goroutine 14 [select]:
github.com/hashicorp/memberlist.(*Memberlist).udpHandler(0xc2080880e0)
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/net.go:344 +0x36d
created by github.com/hashicorp/memberlist.newMemberlist
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/memberlist.go:124 +0xec3

goroutine 16 [select]:
github.com/hashicorp/memberlist.(*Memberlist).triggerFunc(0xc2080880e0, 0x3b9aca00, 0xc208058840, 0xc2080587e0, 0xc208030f20)
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/state.go:105 +0x151
created by github.com/hashicorp/memberlist.(*Memberlist).schedule
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/state.go:71 +0x18a

goroutine 17 [select]:
github.com/hashicorp/memberlist.(*Memberlist).pushPullTrigger(0xc2080880e0, 0xc2080587e0)
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/state.go:123 +0x259
created by github.com/hashicorp/memberlist.(*Memberlist).schedule
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/state.go:77 +0x2cf

goroutine 18 [select]:
github.com/hashicorp/memberlist.(*Memberlist).triggerFunc(0xc2080880e0, 0xbebc200, 0xc2080588a0, 0xc2080587e0, 0xc208030f60)
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/state.go:105 +0x151
created by github.com/hashicorp/memberlist.(*Memberlist).schedule
	/Users/armon/projects/go/src/github.com/hashicorp/memberlist/state.go:83 +0x3b3

goroutine 19 [select]:
github.com/hashicorp/serf/serf.(*Serf).handleReap(0xc20803f520)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/serf.go:1339 +0x281
created by github.com/hashicorp/serf/serf.Create
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/serf.go:370 +0x1b6e

goroutine 20 [select]:
github.com/hashicorp/serf/serf.(*Serf).handleReconnect(0xc20803f520)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/serf.go:1355 +0x106
created by github.com/hashicorp/serf/serf.Create
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/serf.go:371 +0x1b8e

goroutine 21 [select]:
github.com/hashicorp/serf/serf.(*Serf).checkQueueDepth(0xc20803f520, 0x98d750, 0x6, 0xc208094780)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/serf.go:1445 +0x52e
created by github.com/hashicorp/serf/serf.Create
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/serf.go:372 +0x1bcd

goroutine 22 [select]:
github.com/hashicorp/serf/serf.(*Serf).checkQueueDepth(0xc20803f520, 0x98bed0, 0x5, 0xc2080947b0)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/serf.go:1445 +0x52e
created by github.com/hashicorp/serf/serf.Create
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/serf.go:373 +0x1c0f

goroutine 23 [select]:
github.com/hashicorp/serf/serf.(*Serf).checkQueueDepth(0xc20803f520, 0x990cb0, 0x5, 0xc2080947e0)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/serf.go:1445 +0x52e
created by github.com/hashicorp/serf/serf.Create
	/Users/armon/projects/go/src/github.com/hashicorp/serf/serf/serf.go:374 +0x1c51

goroutine 24 [select]:
github.com/hashicorp/serf/command/agent.(*Agent).eventLoop(0xc208010b60)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/command/agent/agent.go:240 +0x41c
created by github.com/hashicorp/serf/command/agent.(*Agent).Start
	/Users/armon/projects/go/src/github.com/hashicorp/serf/command/agent/agent.go:103 +0x1c5

goroutine 25 [IO wait]:
net.(*pollDesc).Wait(0xc2080106f0, 0x72, 0x0, 0x0)
	/Users/armon/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080106f0, 0x0, 0x0)
	/Users/armon/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010690, 0x0, 0x7fc39cbccd70, 0xc2080317a0)
	/Users/armon/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20804a048, 0x0, 0x0, 0x0)
	/Users/armon/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20804a048, 0x0, 0x0, 0x0, 0x0)
	/Users/armon/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/hashicorp/serf/command/agent.(*AgentIPC).listen(0xc208058960)
	/Users/armon/projects/go/src/github.com/hashicorp/serf/command/agent/ipc.go:355 +0x59
created by github.com/hashicorp/serf/command/agent.NewAgentIPC
	/Users/armon/projects/go/src/github.com/hashicorp/serf/command/agent/ipc.go:329 +0x2e5
```

I'm using serf 0.6.4 on 64 bit linux. If you guys need any more information I'd be glad to contribute!

**Comment by armon** [comment]
@jacksontj I just pushed a potential fix (https://github.com/hashicorp/serf/commit/a72c0453da2ba628a013e98bf323a76be4aa1443). Let us know how the python library evolves, would love to play with it!

**Comment by jacksontj** [comment]
Although that patch fixes it IMO the bug is really over in memberlist. I filled a PR with the fix in memberlist (https://github.com/hashicorp/memberlist/pull/57) which would gaurantee that the delegates aren't called if there is no userMsg

**Comment by jacksontj** [comment]
@armon BTW I got this fixed upstream (https://github.com/hashicorp/memberlist/pull/57)

**Comment by armon** [comment]
@jacksontj Thanks!
