### ISSUE TITLE
Serf process not responisive anymore

### ISSUE THREAD

**Issue by jaapdejong** [hashicorp/serf#347]
Hi,

I'm observing this strange error for some time and it seems to only reveal itself after running for around 14 days. 
We are running this on our armv5te boards.
Using the discover option and also using encryption.
Serf versio = 0.6.3

I finally managed to get a trace from serf after it became unresponsive by:
killall -SIGABRT serf
I attached the output.

Any help is appreciated!!

Thanks in advance
Jaap

[trace.txt](https://github.com/hashicorp/serf/files/66572/trace.txt)

**Comment by slackpad** [comment]
Hi @jaapdejong - the last goroutine in there looks fishy:

```
goroutine 62526 [IO wait, 14190 minutes]:
net.(*pollDesc).Wait(0x10950638, 0x72, 0x0, 0x0)
	/golang-cross-1.4.2-r1/go/src/net/fd_poll_runtime.go:84 +0x3c
net.(*pollDesc).WaitRead(0x10950638, 0x0, 0x0)
	/golang-cross-1.4.2-r1/go/src/net/fd_poll_runtime.go:89 +0x38
net.(*netFD).Read(0x10950600, 0x109fb000, 0x1000, 0x1000, 0x0, 0x40011c28, 0x108f74e4)
	/golang-cross-1.4.2-r1/go/src/net/fd_unix.go:242 +0x390
net.(*conn).Read(0x1081c538, 0x109fb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/golang-cross-1.4.2-r1/go/src/net/net.go:121 +0xc8
bufio.(*Reader).fill(0x1093b140)
	/golang-cross-1.4.2-r1/go/src/bufio/bufio.go:97 +0x1d8
bufio.(*Reader).ReadByte(0x1093b140, 0x803dc, 0x0, 0x0)
	/golang-cross-1.4.2-r1/go/src/bufio/bufio.go:196 +0xa0
github.com/ugorji/go/codec.(*ioDecReader).readn1(0x1093dd00, 0x8153c)
	/serf-0.6.3-r12/git/src/github.com/ugorji/go/codec/decode.go:90 +0x54
github.com/ugorji/go/codec.(*msgpackDecDriver).initReadNext(0x108f6430)
	/serf-0.6.3-r12/git/src/github.com/ugorji/go/codec/msgpack.go:540 +0x54
github.com/ugorji/go/codec.(*Decoder).decode(0x1093b2c0, 0x39bc38, 0x108f6470)
	/serf-0.6.3-r12/git/src/github.com/ugorji/go/codec/decode.go:635 +0x54
github.com/ugorji/go/codec.(*Decoder).Decode(0x1093b2c0, 0x39bc38, 0x108f6470, 0x0, 0x0)
	/serf-0.6.3-r12/git/src/github.com/ugorji/go/codec/decode.go:630 +0x88
github.com/hashicorp/serf/command/agent.(*AgentIPC).handleClient(0x1083f320, 0x1096afa0)
	/serf-0.6.3-r12/git/src/github.com/hashicorp/serf/command/agent/ipc.go:426 +0x98
created by github.com/hashicorp/serf/command/agent.(*AgentIPC).listen
	/serf-0.6.3-r12/git/src/github.com/hashicorp/serf/command/agent/ipc.go:355 +0x8f4
```

It seems like it is stuck trying to decode a command. A lot has changed since Serf 0.6.3 was released (we are getting ready to release Serf 0.7 based off master). It is possible for you to try a build from master and/or a newer version of Go?

**Comment by jaapdejong** [comment]
Hi @slackpad 
using the latest commit could be an option, but since it is hard to reproduce the error it would not be easy to know if that helped.
The error comes in two flavors by the way. The first is this deadlock, the second is that serf just dies.
For the moment I will add a watchdog on the serf process. 
Perhaps you have ideas to make the error come up faster?
Can I stress it?
Perhaps code inspection reveals why it becomes unresponsive?
Thanks
Jaap

**Comment by jaapdejong** [comment]
Hi All,
Have got 2 new traces.
Shall I add them?
Send directly?
Thanks & Merry Christmas everybody!!
Jaap

**Comment by jaapdejong** [comment]
Have another log...
[serf-0641c7.log.txt](https://github.com/hashicorp/serf/files/72643/serf-0641c7.log.txt)

**Comment by jaapdejong** [comment]
If needed, I have another 5 logs...

**Comment by jaapdejong** [comment]
Hi @slackpad 

while looking through the other serf issues I found this one: https://github.com/hashicorp/serf/issues/339
Is that possibly related to this bug?

Thanks,
Jaap

**Comment by jaapdejong** [comment]
Hi @slackpad 
have another trace with different cause (I guess) 
This time serf died and left a trace in the log.

`fatal error: runqputslow: queue is not full`

[serf0643ff.log.txt](https://github.com/hashicorp/serf/files/79490/serf0643ff.log.txt)
Hope you can have a look at it...
Cheers,
Jaap

**Comment by jaapdejong** [comment]
Hi @slackpad 
I have seen the same issue now on a serf 0.7.0 system.
No trace unfortunately.
Jaap
