### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by thefosk** [hashicorp/serf#414]
I am receiving the following error when running Serf 0.8 on OSX Sierra:

```
[signal 0xa code=0x2 addr=0xc820200000 pc=0x5fe61]

goroutine 1 [running]:
runtime.throw(0x7cf420, 0x2a)
       	/goroot/src/runtime/panic.go:547 +0x90 fp=0xc82013d3a8 sp=0xc82013d390
runtime.sigpanic()
       	/goroot/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82013d3f8 sp=0xc82013d3a8
runtime.memmove(0xc82013d458, 0xc820013830, 0xffffffffec780e42)
       	/goroot/src/runtime/memmove_amd64.s:83 +0x91 fp=0xc82013d400 sp=0xc82013d3f8
runtime.deferreturn(0xc820052118)
       	/goroot/src/runtime/panic.go:299 +0x9c fp=0xc82013d458 sp=0xc82013d400
github.com/hashicorp/serf/client.(*RPCClient).send(0x8218e0, 0xc820170150, 0x8218d8, 0x640780, 0x53a620, 0x53ab20)
       	/gopath/src/github.com/hashicorp/serf/client/rpc_client.go:103 +0x315 fp=0xc82013d510 sp=0xc82013d458

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
       	/goroot/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
       	/goroot/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
       	/goroot/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [runnable]:
syscall.Read(0x6, 0xc82017ca60, 0x1000, 0x1000, 0x6, 0x0, 0x0)
       	/goroot/src/syscall/syscall_unix.go:160
time.readFile(0x70d550, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0)
       	/goroot/src/time/sys_unix.go:34 +0x19b
time.loadZoneFile(0x0, 0x0, 0x70d550, 0xe, 0x0, 0x0, 0x0)
       	/goroot/src/time/zoneinfo_read.go:206 +0x199
time.initLocal()
       	/goroot/src/time/zoneinfo_unix.go:59 +0x77
sync.(*Once).Do(0xa59180, 0x822b08)
       	/goroot/src/sync/once.go:44 +0xe4
time.(*Location).get(0xa3b800, 0xc820030078)
       	/goroot/src/time/zoneinfo.go:76 +0x58
time.Time.abs(0xecf77dfef, 0x24e4e688, 0xa3b800, 0x0)
       	/goroot/src/time/time.go:251 +0xc5
time.Time.date(0xecf77dfef, 0x24e4e688, 0xa3b800, 0x109000000000001, 0x0, 0xc820176000, 0x76, 0xc820176000)
       	/goroot/src/time/time.go:674 +0x33
time.Time.Date(0xecf77dfef, 0x24e4e688, 0xa3b800, 0x0, 0x0, 0x0)
       	/goroot/src/time/time.go:291 +0x38
log.(*Logger).formatHeader(0xc82000a230, 0xc82000a260, 0xecf77dfef, 0x24e4e688, 0xa3b800, 0x0, 0x0, 0x0)
       	/goroot/src/log/log.go:97 +0x249
log.(*Logger).Output(0xc82000a230, 0x2, 0xc820176000, 0x76, 0x0, 0x0)
       	/goroot/src/log/log.go:161 +0x1dd
log.Printf(0x7ddca0, 0x38, 0xc82017df68, 0x1, 0x1)
       	/goroot/src/log/log.go:289 +0x80
github.com/hashicorp/serf/client.(*RPCClient).listen(0xc8200520e0)
       	/gopath/src/github.com/hashicorp/serf/client/rpc_client.go:818 +0x174
created by github.com/hashicorp/serf/client.ClientFromConfig
       	/gopath/src/github.com/hashicorp/serf/client/rpc_client.go:147 +0x595
```

**Comment by slackpad** [comment]
Hi @thefosk thanks for opening an issue. Any context about what you were doing when you saw this (looks like maybe running a CLI command)? This was built with Go 1.6.3 which should work on Sierra (previous versions of Go would have had known issues).

**Comment by thefosk** [comment]
By running the "leave" and "members" CLI commands (I haven't tested the others).

 Marco Palladino | CTO @ Mashape | mashape.com | +1 (415) 361-3858

**Comment by thefosk** [comment]
It also happens with `serf event` so I think it's safe to assume it happens on _almost_ every command

**Comment by thefosk** [comment]
@slackpad any chance we could try to compile Serf with a newer version of Go and give it a try?

**Comment by thefosk** [comment]
Tried to build it myself on OSX 10.12 Sierra with Go 1.7.3 - currently failing: https://gist.github.com/thefosk/1a26fe14aee79cf638653a223a293a6a

I am not a Go expert, so maybe you will find something obvious from the logs.
