### ISSUE TITLE
closing eventCh after shutdown panics

### ISSUE THREAD

**Issue by predmond** [hashicorp/serf#462]
I'm doing something like:
```
config := serf.DefaultConfig()
config.Init()
eventCh := make(chan serf.Event, 16)
config.EventCh = eventCh
```
...
then when I shutdown I do:

```
s.Leave()                                                                   
s.Shutdown()                                                                
<-s.ShutdownCh()                                                            
close(eventCh)
```

But I get a panic:
```
panic: send on closed channel

goroutine 52 [running]:
swarm/vendor/github.com/hashicorp/serf/serf.(*serfQueries).stream(0xc4204b8150)
	/home/predmond/src/swarm/go/src/swarm/vendor/github.com/hashicorp/serf/serf/internal_query.go:87 +0x15a
created by swarm/vendor/github.com/hashicorp/serf/serf.newSerfQueries
	/home/predmond/src/swarm/go/src/swarm/vendor/github.com/hashicorp/serf/serf/internal_query.go:73 +0xfb
```

I've tested with my vendor directory up-to-date. As far as I know it's my responsibility to close the event channel and doing it after shutdown should be safe..

**Comment by predmond** [comment]
Oops. My mistake. I should not close the channel after shutdown.
